blog/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls'))
]

main/urls.py
from django.urls import path

from main import views
urlpatterns = [
    path('',views.index,name='index'),
    path('article/<int:pk>',views.article,name='get_article'),
    path('author/<int:pk>',views.author,name='get_author'),
    path('article',views.create_article,name='create_article')
]

main/models.py
from django.db import models

# Create your models here.
class Author(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name
    

class Article(models.Model):
    name=  models.CharField(max_length=255)
    created_at= models.DateTimeField(auto_now_add=True)
    content= models.TextField()

    author= models.ManyToManyField('Author')

    def __str__(self):
        return self.name

main/views.py
from django.shortcuts import render, get_object_or_404
from main import models
# Create your views here.


def index(request):
    latest_articles = models.Article.objects.order_by('-created_at')[:10]
    context ={
        'latest_articles':latest_articles
    }

    return render(request,'main/index.html',context)

def article(request,pk):
    # article= models.Article.objects.get(pk=pk)
    article = get_object_or_404(models.Article,pk=pk)
    context={
        "article":article
    }
    return render(request,'main/article.html',context)

def author(request,pk):
    author = get_object_or_404(models.Author,pk=pk)
    context={
        "author":author
    }
    return render(request,'main/author.html',context)

def create_article(request):
    authors = models.Author.objects.all()
    context={
        "authors":authors,
    }
    if request.method=="POST":
        article_data = {
            'name': request.POST['name'],
            'content': request.POST['content']
        }
        article = models.Article.objects.create(**article_data)
        author = models.Author.objects.filter(pk= request.POST['author'])
        article.author.set(author)
        context["success"] = True

    return render(request,'main/create_article.html',context)

templates/main/article.html
{% extends 'main/base.html' %}
{% block head %}
    <title>{{ article.name }}</title>
{% endblock %}
{% block content %}
    <h1>{{ article.name }}</h1>
    <h3>Created At : {{ article.created_at }}</h3>
    <p>
        {{ article.content }}
    </p>
    <h3>Written By : 
        {% for author in article.author.all %}
            <a href="{% url 'get_author' author.id %}">
            {{ author.name }},
            </a>
        {% endfor %}
    </h3>

{% endblock %}

templates/main/author.html
{% extends 'main/base.html' %}
{% block head %}
    <title>{{ author.name }}</title>
{% endblock %}
{% block content %}
    <h1>Name: {{ author.name }}</h1>
    <h4> Articles written </h4>
    <ul>
        {% for article in author.article_set.all %}
            <li>
                <a href="{% url 'get_article' article.id %}">
                    {{ article.name}}
                </a>
            </li>
        {% endfor %}
    </ul>
    

{% endblock %}

templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block head %} {% endblock %}
</head>
<body>
    {% block content %} {% endblock %}
</body>
</html>

templates/main/create_article.html
{% extends 'main/base.html' %}
{% block head %}
    <title>Create An Article </title>
{% endblock %}
{% block content %}

    {% if success %}
        <h4>Form submitted successfully</h4>

    {% endif %}

    <h1>Create An Article</h1>
    <form method="POST">
        {% csrf_token %}
        <input type="text" name="name" placeholder="Article name"/>
        <textarea name="content" placeholder="content"></textarea>
        <select name="author">
            {% for author in authors %}
                <option value="{{ author.id }}">{{ author.name }}</option>  
            {% endfor %}
        </select>

        <button type="submit">Submit</button>
        <button type="reset">reset</button>

    </form>

{% endblock %}

templates/main/index.html
{% extends 'main/base.html' %}
{% block head %}
    <title>Blog </title>
{% endblock %}
{% block content %}
    <h1>Blog Application</h1>
    <h3>Latest Articles </h3>
    <ul>
        {% for article in latest_articles %}
            <li>
                <a href="{% url 'get_article' article.id %}" >
                    {{ article.name }}
                </a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}